name: clean_arch
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^2.0.1
  flutter_bloc: ^6.0.0
  equatable: ^1.2.0
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  http: 
  shared_preferences: ^0.5.3+4
  cupertino_icons: ^0.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:
  uses-material-design: true
